### ISSUE TITLE
Missing Features Tracker

### ISSUE THREAD

**Issue by Makowo** [trophy-place/community#19]
Megapost of things I can think of that is currently missing, Feel free to edit and or make separate issues and tag them here

### Backend stuff
- [ ] Latest games / DLC from PSN: Currently our solution to this is just the latest games added to the database, which is fine but we should ideally have some way of getting this from PSN?

### User stuff
- [ ] Trophy Cabinet: Not sure how or where or if we want to implement them, but it do be a thing
- [ ] User Milestones: stuff like 1k trophy, blah blah
- [ ] Statistics Page

### Game stuff
- [ ] Series page

**Comment by TheYuriG** [comment]
> * [ ]  Latest games / DLC from PSN: Currently our solution to this is just the latest games added to the database, which is fine but we should ideally have some way of getting this from PSN?

I have a feeling that every website does this based on fetching data from an account that isn't ranked, so not displayed on the owners/achievers. The backend doesn't allow us to fetch *some* data without associating it with a player, I'm pretty sure. You can't get rarities at very least, can't remember what else. We can look into it if someone provides a way.
